version: "3.1"
services:
  bycar_api:
    image: "node:16"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    networks:
      - internal
      - proxy
    command: "yarn serve:prod"
    labels:
      - traefik.enable=true
      - traefik.http.routers.staging-admin.rule=Host(`staging-admin.bycar.in.ua`)
      - traefik.http.routers.staging-admin.entrypoints=websecure
      - traefik.http.routers.staging-admin.tls=true
      - traefik.http.routers.staging-admin.tls.certresolver=letsencrypt-resolver
      - traefik.http.services.staging-admin.loadbalancer.server.port=5000

networks:
  internal:
    external: false
  proxy:
    external: true
      