version: "3.1"
services:
  bycar_api:
    image: "node:16"
    container_name: ${SERVICE_NAME}
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    networks:
      - proxy
    command: "yarn serve"
    restart: "always"
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_DOMAIN}`)
      - traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure
      - traefik.http.routers.${SERVICE_NAME}.tls=true
      - traefik.http.routers.${SERVICE_NAME}.tls.certresolver=letsencrypt-resolver
      - traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=3010
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true

networks:
  proxy:
    external: true
