name: deploy

on:
  push:
    branches: [master]
  pull_request: [master]

  workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: setup node environment
          uses: actions/setup-node@v3
          env:
            VITE_API_HOST: ${{ secrets.VITE_API_HOST }}
            VITE_CDN_HOST: ${{ secrets.VITE_CDN_HOST }}
            VITE_COOKIE_DOMAIN: ${{ secrets.VITE_COOKIE_DOMAIN }}

        - name: install and build
          run: |
            npm ci
            npm run build

        - name: S3 sync
          uses: jakejarvis/s3-sync-action@master
          with:
            args: --acl public-read --delete
          env:
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: eu-north-1

        - name: invalidate CloudFront
          uses: chetan/invalidate-cloudfront-action@v2
          env:
            DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }}
            PATHS: "/*"
            AWS_REGION: "eu-north-1"
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
